name: Build and Sign Common Library

on:
  push:
    branches:
      - dev # off - to turn off

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ secrets.HARBOR_REGISTRY }}/${{ github.event.repository.name }}:1.0.0 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.HARBOR_REGISTRY }}/${{ github.event.repository.name }}:1.0.0

  sign:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Prepare Cosign Key
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${{ secrets.HARBOR_REGISTRY }}/${{ github.event.repository.name }}:1.0.0
