name: Build, Sign - Common

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMON_IMAGE: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.PROJECT_NAME }}-${{ github.ref_name }}/common:1.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install and Verify CA Certificate
        run: |
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}
          echo "${{ secrets.HARBOR_CA_CRT }}" | sudo tee /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt > /dev/null
          sudo cp /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt /usr/local/share/ca-certificates/harbor-ca.crt
          sudo update-ca-certificates
          sudo systemctl restart docker
          sudo ls -l /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.COMMON_IMAGE }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.COMMON_IMAGE }}

  sign:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign and CA Certificate
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}
          echo "${{ secrets.HARBOR_CA_CRT }}" | sudo tee /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt > /dev/null
          sudo cp /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt /usr/local/share/ca-certificates/harbor-ca.crt
          sudo update-ca-certificates
          sudo systemctl restart docker

      - name: Prepare Cosign Key
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.PROJECT_NAME }}-${{ github.ref_name }}/${{ github.event.repository.name }}:1.0.0
